#!/usr/bin/env bash
set -euo pipefail

cat <<EOF
APP_NAME=${APP_NAME:-}
PROJECT_TYPE=${PROJECT_TYPE:-}
SERVER_HOST=${SERVER_HOST:-}
SERVER_USER=${SERVER_USER:-}
DEPLOY_DIR=${DEPLOY_DIR:-}
SERVICE_NAME=${SERVICE_NAME:-}
APP_PORT=${APP_PORT:-}
PUBLIC_URL=${PUBLIC_URL:-}
DOMAIN=${DOMAIN:-}
NGINX_CONF=${NGINX_CONF:-}
SYSTEMD_UNIT=${SYSTEMD_UNIT:-}
CORE_CHECK=${CORE_CHECK:-}
LAST_DEPLOY_AT=${LAST_DEPLOY_AT:-}
LINUX_ADAPTATIONS=${LINUX_ADAPTATIONS:-}
EOF
